wallpaper {
    monitor = DP-1
    path = ~/Pictures/wallpapers/699287.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/Pictures/wallpapers/699287.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = ~/Pictures/wallpapers/minimal-waterfall-in-mountains-scenery-beautiful-5k-4a-1366x768.jpg
}

wallpaper {
    monitor = 
    path = ~/Pictures/wallpapers/wallhaven-gwj6o7.jpg
    fit_mode = cover
}


